name: Send_Telagram_Message.py

on:
  push:
    branches:
      - main 

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Run script
        run: python make_file.py

      - name: commit files
        run: |
          git config --local user.email "aminachak8182@gmail.com"
          git config --local user.name "Clancyov"
          git add -A
          git status
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PUSHER_TOKEN }}
          branch: main 
        
