name: Send_Telagram_Message.py

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install telethon
          
      - name: Run script
        env:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          PHONE_NUMBER: ${{ secrets.TELEGRAM_PHONE_NUMBER }}
        run: python Send_Telagram_Message.py
        
